### PR TITLE
fixed babel register call for mocha

### PR DESCRIPTION
**Pull request by MrBaptastic**
Easy fix

### CODE REVIEW

**Comment by tjstebbing** [comment]
LGTM 👍

**Comment by SomeoneWeird** [comment]
We don't even include `babel-core` in `devDependencies` in our project skeleton, we should probably fix that. I also think `babel-core/register` has been deprecated in favour of `babel-register`.

**Comment by SomeoneWeird** [comment]
ping @pomke @joshgillies

**Comment by joshgillies** [comment]
@SomeoneWeird these deps should come from https://github.com/iflix-letsplay/rukus/blob/master/bin/rukus.js#L79

**Comment by SomeoneWeird** [comment]
Why do we have them there and not in the `project-skel/package.json`? Seems a little odd.

**Comment by joshgillies** [comment]
@SomeoneWeird I've no idea. Ping #15

**Pull request closed without merging**
